/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ff7a2f",
        "primary": "#ff9159",
        "primary-fixed-dim": "#f66700",
        "tertiary-container": "#ebebeb",
        "inverse-surface": "#f8f9ff",
        "on-surface-variant": "#a8abb3",
        "on-primary-fixed-variant": "#4f1c00",
        "secondary-fixed-dim": "#bed1e7",
        "outline-variant": "#44484f",
        "background": "#0a0e14",
        "inverse-on-surface": "#51555c",
        "on-secondary": "#3e5063",
        "on-primary": "#531e00",
        "surface-container-highest": "#20262f",
        "secondary-dim": "#bed1e7",
        "primary-dim": "#ff7524",
        "tertiary-fixed": "#ffffff",
        "error-container": "#b92902",
        "surface-container-low": "#0f141a",
        "surface-container-lowest": "#000000",
        "surface": "#0a0e14",
        "surface-container-high": "#1b2028",
        "surface-bright": "#262c36",
        "inverse-primary": "#a14100",
        "secondary": "#ccdff6",
        "tertiary-dim": "#ebebeb",
        "on-primary-container": "#401500",
        "error": "#ff7351",
        "tertiary-fixed-dim": "#f0f1f1",
        "on-tertiary-fixed-variant": "#6c6d6e",
        "on-tertiary": "#5e5f60",
        "on-secondary-container": "#bfd2e9",
        "on-background": "#f1f3fc",
        "on-tertiary-container": "#555757",
        "secondary-fixed": "#ccdff6",
        "error-dim": "#d53d18",
        "on-secondary-fixed": "#2b3d4f",
        "surface-container": "#151a21",
        "secondary-container": "#36485b",
        "surface-tint": "#ff9159",
        "primary-container": "#ff7a2f",
        "outline": "#72757d",
        "surface-variant": "#20262f",
        "surface-dim": "#0a0e14",
        "on-secondary-fixed-variant": "#485a6d",
        "tertiary": "#f9f9f9",
        "on-error": "#450900",
        "on-tertiary-fixed": "#4f5051",
        "on-surface": "#f1f3fc",
        "on-primary-fixed": "#000000",
        "on-error-container": "#ffd2c8",
        // Tier colors mapping to css
        'tier-common': '#5A6A8A',
        'tier-rare': '#3B82F6',
        'tier-epic': '#A855F7',
        'tier-legendary': '#EAB308',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
