/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#ff7a2f',
        'primary': '#ff9159',
        'primary-fixed-dim': '#f66700',
        'on-primary-fixed': '#000000',
        'on-primary': '#531e00',
        'primary-container': '#ff7a2f',
        'on-primary-container': '#401500',
        'primary-dim': '#ff7524',
        'background': '#0a0e14',
        'on-background': '#f1f3fc',
        'surface': '#0a0e14',
        'on-surface': '#f1f3fc',
        'on-surface-variant': '#a8abb3',
        'surface-container': '#151a21',
        'surface-container-low': '#0f141a',
        'surface-container-lowest': '#000000',
        'surface-container-high': '#1b2028',
        'surface-container-highest': '#20262f',
        'surface-bright': '#262c36',
        'surface-variant': '#20262f',
        'surface-dim': '#0a0e14',
        'surface-tint': '#ff9159',
        'outline': '#72757d',
        'outline-variant': '#44484f',
        'secondary': '#ccdff6',
        'secondary-container': '#36485b',
        'on-secondary': '#3e5063',
        'on-secondary-container': '#bfd2e9',
        'error': '#ff7351',
        'error-container': '#b92902',
        'on-error': '#450900',
        'on-error-container': '#ffd2c8',
        'inverse-surface': '#f8f9ff',
        'inverse-on-surface': '#51555c',
        'inverse-primary': '#a14100',
        // Tier colors
        'tier-common': '#5A6A8A',
        'tier-rare': '#3B82F6',
        'tier-epic': '#8B5CF6',
        'tier-legendary': '#F5C842',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
